/**
 * Constants for message types exchanged between webview and extension
 */

/**
 * Message types sent FROM webview TO extension
 */
export const INCOMING_MESSAGE_TYPES = {
  DEBUG_LOG: 'DEBUG_LOG',
  GET_METADATA_INPUT_LIST: 'GET_METADATA_INPUT_LIST',
  READ_SETTINGS_FILE: 'READ_SETTINGS_FILE',
  EXECUTE_API: 'EXECUTE_API',
} as const;

/**
 * Message types sent FROM extension TO webview
 */
export const OUTGOING_MESSAGE_TYPES = {
  SETTINGS_FILE_CONTENT: 'SETTINGS_FILE_CONTENT',
  SETTINGS_FILE_NOT_FOUND: 'SETTINGS_FILE_NOT_FOUND',
  GET_METADATA_INPUT_LIST_RESPONSE: 'GET_METADATA_INPUT_LIST_RESPONSE',
  API_EXECUTION_RESULT: 'API_EXECUTION_RESULT',
  API_EXECUTION_ERROR: 'API_EXECUTION_ERROR',
} as const;


